--- 
apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata: 
  name: mgo-quickstart
  namespace: demo
spec: 
  replicas: 1
  storage: 
    accessModes: 
      - ReadWriteOnce
    resources: 
      requests: 
        storage: 1Gi
    storageClassName: hostpath
  storageType: Durable
  terminationPolicy: DoNotTerminate
  updateStrategy: 
    type: RollingUpdate
  version: 3.4-v2
